"""
Mapeo de Ramos CELER → Subramos MAVISO
======================================
Este archivo contiene los mapeos para convertir:
1. Aseguradoras de CELER a Aseguradoras de MAVISO (nombres exactos para dropdowns)
2. Ramos de CELER a Subramos válidos de MAVISO
"""

# =============================================================================
# MAPEO DE ASEGURADORAS: CELER → MAVISO
# =============================================================================
# Nota: Los nombres en MAVISO deben coincidir EXACTAMENTE con los rangos definidos
# en la hoja 'dropdown_list' (sin tildes, espacios exactos)

MAPEO_ASEGURADORAS = {
    # CELER                                      # MAVISO (nombre exacto del rango)
    "ALLIANZ SEGUROS S.A":                       "ALLIANZ SEGUROS SA",
    "ASEGURADORA GRANCOLOMBIANA S.A.":           "GRANCOLOMBIANA DE FIANZAS SAS",  # Similar
    "ASEGURADORA SOLIDARIA DE COLOMBIA":         "ASEGURADORA SOLIDARIA DE COLOMBIA",
    "ASSIST CARD":                               "ASSIST CARD DE COLOMBIA SAS",
    "AXA COLPATRIA SEGUROS S.A.":                "AXA COLPATRIA SEGUROS SA",  # Puede ir a VIDA también según ramo
    "CEM":                                       "COOMEVA EXPERIENCIA MEDICA SAS",
    "CHUBB DE COLOMBIA COMPAÑÍA SEGUROS S A":    "CHUBB SEGUROS COLOMBIA SA",
    "COLMENA VIDA Y RIESGOS PROFESIONES SA":     "COLMENA SEGUROS",
    "COMPAÑIA DE MEDICINA PREPAGADA COLSANITAS S.A": "COMPAÑIA DE MEDICINA PREPAGADA COLSANITAS SA",
    "COMPAÑÍA MUNDIAL DE SEGUROS S A":           "SEGUROS MUNDIAL",
    "COOMEVA":                                   "COOMEVA MEDICINA PREPAGADA SA",  # O EXPERIENCIA MEDICA según producto
    "EMERMÉDICA S.A":                            "EMERMEDICA SA SERVICIOS DE AMBULANCIA PREPAGADOS",
    "FUNER SAN VICENTE":                         "FUNERARIA SAN VICENTE SA",
    "HDI SEGUROS SA":                            "HDI SEGUROS",
    "LA EQUIDAD SEGUROS OC":                     "LA EQUIDAD SEGUROS GENERALES",
    "LA PREVISORA S A COMPAÑÍA DE SEGUROS":      "LA PREVISORA S A COMPAÑIA DE SEGUROS",
    "LIBERTY SEGUROS S A":                       None,  # ⚠️ NO EXISTE EN MAVISO
    "MAGENTA SEGUROS LTDA":                      "MAGENTA ASISTANCE SAS",
    "MAPFRE SEGUROS DE COLOMBIA S A":            "MAPFRE SEGUROS GENERALES",
    "MEDISANITAS":                               "MEDISANITAS SAS COMPAÑIA DE MEDICINA PREPAGADA",
    "POSITIVA COMPAÑIA DE SEGUROS S.A.":         "POSITIVA COMPAÑIA DE SEGUROS SA",
    "SBS SEGUROS COLOMBIA S.A":                  "SBS SEGUROS COLOMBIA SA",
    "SEGUROS BOLIVAR":                           "COMPAÑIA DE SEGUROS BOLIVAR SA",
    "SEGUROS DEL ESTADO S A":                    "SEGUROS DEL ESTADO SA",  # O VIDA según ramo
    "SURAMERICANA S.A.":                         "SEGUROS GENERALES SURAMERICANA S A",  # O VIDA según ramo
    "ZURICH COLOMBIA SEGUROS S.A":               "ZURICH COLOMBIA SEGUROS SA",
}

# =============================================================================
# MAPEO ESPECIAL: Aseguradoras que van a VIDA o GENERALES según el ramo
# =============================================================================
ASEGURADORAS_DOBLES = {
    # Aseguradora CELER: {ramos_que_van_a_vida: aseguradora_vida, default: aseguradora_general}
    "ALLIANZ SEGUROS S.A": {
        "ramos_vida": ["ACCIDENTES PERSONALES", "VIDA INDIVIDUAL", "VIDA COLECTIVO", 
                       "SALUD FAMILIAR", "SALUD COLECTIVA"],
        "aseguradora_vida": "ALLIANZ SEGUROS DE VIDA SA",
        "aseguradora_general": "ALLIANZ SEGUROS SA"
    },
    "AXA COLPATRIA SEGUROS S.A.": {
        "ramos_vida": ["ARL", "MAS VIDA", "VIDA INDIVIDUAL", "VIDA COLECTIVO"],
        "aseguradora_vida": "AXA COLPATRIA SEGUROS DE VIDA SA",
        "aseguradora_general": "AXA COLPATRIA SEGUROS SA"
    },
    "SURAMERICANA S.A.": {
        "ramos_vida": ["ACCIDENTES PERSONALES", "ACCIDENTES JUVENILES", "ARL", 
                       "VIDA GRUPO COLECTIVO", "VIDA INDIVIDUAL", "RENTA EDUCATIVA",
                       "PLAN COMPLEMENTARIO", "PLAN COMPLEMENTARIO COLECTIVO", 
                       "PLAN COMPLEMENTARIO FAMILIAR", "SALUD COLECTIVA", 
                       "SALUD FAMILIAR", "SALUD PARA TODOS"],
        "aseguradora_vida": "SEGUROS DE VIDA SURAMERICANA SA",
        "aseguradora_general": "SEGUROS GENERALES SURAMERICANA S A"
    },
    "SEGUROS DEL ESTADO S A": {
        "ramos_vida": ["ACCIDENTES PERSONALES"],
        "aseguradora_vida": "SEGUROS DE VIDA DEL ESTADO",
        "aseguradora_general": "SEGUROS DEL ESTADO SA"
    },
}

# =============================================================================
# MAPEO DE RAMOS CELER → SUBRAMOS MAVISO
# =============================================================================
# Organizado por aseguradora para facilitar el mantenimiento

MAPEO_RAMOS = {
    # -------------------------------------------------------------------------
    # ALLIANZ SEGUROS SA (Generales)
    # -------------------------------------------------------------------------
    ("ALLIANZ SEGUROS SA", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("ALLIANZ SEGUROS SA", "MI PYME"): "MULTIRRIESGO EMPRESARIAL",  # Con doble R
    ("ALLIANZ SEGUROS SA", "MULTIRIESGO EMPRESARIAL"): "MULTIRRIESGO EMPRESARIAL",
    ("ALLIANZ SEGUROS SA", "MULTIRIESGO RESIDENCIAL"): "HOGAR",
    ("ALLIANZ SEGUROS SA", "RESPONSABILIDAD CIVIL"): "RC DIRECTORES Y ADMINISTRADORES",  # Revisar caso por caso
    ("ALLIANZ SEGUROS SA", "TRANSPORTES DE MERCANCIAS"): "TRANSPORTES DE MERCANCIAS",
    
    # ALLIANZ SEGUROS DE VIDA SA
    ("ALLIANZ SEGUROS DE VIDA SA", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    ("ALLIANZ SEGUROS DE VIDA SA", "SALUD FAMILIAR"): "SALUD MEDICALL CARE",  # O GOLD, PLUS según nivel
    ("ALLIANZ SEGUROS DE VIDA SA", "VIDA COLECTIVO"): "VIDA GRUPO CONTRIBUTIVA",
    ("ALLIANZ SEGUROS DE VIDA SA", "VIDA INDIVIDUAL"): "VIDA ACTUAL",
    
    # -------------------------------------------------------------------------
    # ASEGURADORA SOLIDARIA DE COLOMBIA
    # -------------------------------------------------------------------------
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "ACCIDENTES DE PASAJEROS"): "ACCIDENTES PERSONALES",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "ACCIDENTES JUVENILES"): "ACCIDENTES JUVENILES",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "MANEJO"): "MANEJO",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "MANEJO ENTIDADES FINANCIERAS"): "INFIDELIDAD DE RIESGSOS FINANCIEROS",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "MAQUINARIA Y EQUIPO"): "MAQUINARIA Y EQUIPO",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "MULTIRIESGO COPROPIEDADES"): "COPROPIEDADES",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "MULTIRIESGO RESIDENCIAL"): "HOGAR",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "RESPONSABILIDAD CIVIL"): "RC DERIVADA DE CUMPLIMIENTO",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "SOAT"): "SOAT",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "TODO RIESGO DAÑOS MATERIALES"): "TODO RIESGO DAÑOS MATERIALES",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "TRANSPORTE DE VALORES"): "TRANSPORTE DE VALORES",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "TRANSPORTES DE MERCANCIAS"): "TRANSPORTES DE MERCANCIAS",
    ("ASEGURADORA SOLIDARIA DE COLOMBIA", "VIDA GRUPO COLECTIVO"): "VIDA GRUPO CONTRIBUTIVO",
    
    # -------------------------------------------------------------------------
    # ASSIST CARD
    # -------------------------------------------------------------------------
    ("ASSIST CARD DE COLOMBIA SAS", "ASIST CARD"): "ASSIST CARD",
    
    # -------------------------------------------------------------------------
    # AXA COLPATRIA
    # -------------------------------------------------------------------------
    ("AXA COLPATRIA SEGUROS SA", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("AXA COLPATRIA SEGUROS SA", "MULTIRIESGO COPROPIEDADES"): "COPROPIEDADES",
    ("AXA COLPATRIA SEGUROS SA", "SOAT"): None,  # No disponible, manejar especialmente
    
    ("AXA COLPATRIA SEGUROS DE VIDA SA", "ARL"): "ARL",
    ("AXA COLPATRIA SEGUROS DE VIDA SA", "MAS VIDA"): "MAS VIDA",
    ("AXA COLPATRIA SEGUROS DE VIDA SA", "VIDA INDIVIDUAL"): "VIDA GRUPO CONTRIBUTIVA",
    
    # -------------------------------------------------------------------------
    # CEM / COOMEVA
    # -------------------------------------------------------------------------
    ("COOMEVA EXPERIENCIA MEDICA SAS", "AREA PROTEGIDA"): "CEM",
    ("COOMEVA EXPERIENCIA MEDICA SAS", "MEDICINA PREPAGADA COLECTIV"): "MEDICINA PREPAGADA FAMILIAR",
    
    ("COOMEVA MEDICINA PREPAGADA SA", "EMERGENCIAS MÉDICAS"): "AREA PROTEGIDA",
    ("COOMEVA MEDICINA PREPAGADA SA", "MEDICINA PREPAGADA COLECTIV"): "MEDICINA PREPAGADA COLECTIV",
    ("COOMEVA MEDICINA PREPAGADA SA", "MEDICINA PREPAGADA FAMILIAR"): "MEDICINA PREPAGADA FAMILIAR",
    
    # -------------------------------------------------------------------------
    # CHUBB
    # -------------------------------------------------------------------------
    ("CHUBB SEGUROS COLOMBIA SA", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    ("CHUBB SEGUROS COLOMBIA SA", "MULTIRIESGO EMPRESARIAL"): "MULTIRRIESGO EMPRESARIAL",
    ("CHUBB SEGUROS COLOMBIA SA", "RESPONSABILIDAD CIVIL"): "RC DIRECTORES Y ADMINISTRADORES",
    
    # -------------------------------------------------------------------------
    # COLMENA
    # -------------------------------------------------------------------------
    ("COLMENA SEGUROS", "ARL"): "ARL COLMENA",
    ("COLMENA SEGUROS", "SEGURO EXEQUIAL"): "SEGUROS EXEQUIALES",
    ("COLMENA SEGUROS", "VIDA GRUPO COLECTIVO"): "VIDA GRUPO",
    
    # -------------------------------------------------------------------------
    # COLSANITAS
    # -------------------------------------------------------------------------
    ("COMPAÑIA DE MEDICINA PREPAGADA COLSANITAS SA", "MEDICINA PREPAGADA COLECTIV"): "MEDICINA PREPAGADA COLECTIV",
    
    # -------------------------------------------------------------------------
    # MUNDIAL
    # -------------------------------------------------------------------------
    ("SEGUROS MUNDIAL", "ARRENDAMIENTO"): "ARRENDAMIENTO",
    ("SEGUROS MUNDIAL", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("SEGUROS MUNDIAL", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("SEGUROS MUNDIAL", "RESPONSABILIDAD CIVIL"): "RC DERIVADA DE CUMPLIMIENTO",
    ("SEGUROS MUNDIAL", "TRANSPORTES DE MERCANCIAS"): None,  # No disponible
    
    # -------------------------------------------------------------------------
    # EMERMÉDICA
    # -------------------------------------------------------------------------
    ("EMERMEDICA SA SERVICIOS DE AMBULANCIA PREPAGADOS", "EMERGENCIAS MÉDICAS"): "EMERGENCIAS MÉDICAS",
    
    # -------------------------------------------------------------------------
    # FUNER SAN VICENTE
    # -------------------------------------------------------------------------
    ("FUNERARIA SAN VICENTE SA", "SEGUROS EXEQUIALES"): "SEGUROS EXEQUIALES",
    
    # -------------------------------------------------------------------------
    # GRANCOLOMBIANA
    # -------------------------------------------------------------------------
    ("GRANCOLOMBIANA DE FIANZAS SAS", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("GRANCOLOMBIANA DE FIANZAS SAS", "RESPONSABILIDAD CIVIL"): "RESPONSABILIDAD CIVIL",
    
    # -------------------------------------------------------------------------
    # HDI
    # -------------------------------------------------------------------------
    ("HDI SEGUROS", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONAL",
    ("HDI SEGUROS", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("HDI SEGUROS", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("HDI SEGUROS", "MULTIRIESGO RESIDENCIAL"): "HOGAR",
    
    # -------------------------------------------------------------------------
    # LA EQUIDAD
    # -------------------------------------------------------------------------
    ("LA EQUIDAD SEGUROS GENERALES", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    ("LA EQUIDAD SEGUROS GENERALES", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("LA EQUIDAD SEGUROS GENERALES", "MANEJO"): "MANEJO",
    ("LA EQUIDAD SEGUROS GENERALES", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    
    # -------------------------------------------------------------------------
    # LA PREVISORA
    # -------------------------------------------------------------------------
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "MANEJO"): "MANEJO",
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "RC SERVIDORES PUBLICOS"): "RC PREDIOS LABORES Y OPERACIONES",
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "RESPONSABILIDAD CIVIL"): "RC PREDIOS LABORES Y OPERACIONES",
    ("LA PREVISORA S A COMPAÑIA DE SEGUROS", "VIDA COLECTIVO"): "VIDA GRUPO COLECTIVO",
    
    # -------------------------------------------------------------------------
    # LIBERTY - NO EXISTE EN MAVISO
    # -------------------------------------------------------------------------
    # Liberty no tiene dropdown en Maviso, estos registros necesitan revisión manual
    
    # -------------------------------------------------------------------------
    # MAGENTA
    # -------------------------------------------------------------------------
    ("MAGENTA ASISTANCE SAS", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    ("MAGENTA ASISTANCE SAS", "EMERGENCIAS MÉDICAS"): "EMERGENCIAS MÉDICAS",
    ("MAGENTA ASISTANCE SAS", "TELEMEDICINA"): "EMERGENCIAS MÉDICAS",  # Más cercano
    
    # -------------------------------------------------------------------------
    # MAPFRE
    # -------------------------------------------------------------------------
    ("MAPFRE SEGUROS GENERALES", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    
    # -------------------------------------------------------------------------
    # MEDISANITAS
    # -------------------------------------------------------------------------
    ("MEDISANITAS SAS COMPAÑIA DE MEDICINA PREPAGADA", "MEDICINA PREPAGADA COLECTIV"): "MEDICINA PREPAGADA",
    
    # -------------------------------------------------------------------------
    # POSITIVA
    # -------------------------------------------------------------------------
    ("POSITIVA COMPAÑIA DE SEGUROS SA", "ACCIDENTES ESCOLARES"): "ACCIDENTES ESCOLARES",
    
    # -------------------------------------------------------------------------
    # SBS
    # -------------------------------------------------------------------------
    ("SBS SEGUROS COLOMBIA SA", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONAL",
    ("SBS SEGUROS COLOMBIA SA", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("SBS SEGUROS COLOMBIA SA", "INCENDIO"): "MULTIRIESGO EMPRESARIAL",
    ("SBS SEGUROS COLOMBIA SA", "MAQUINARIA Y EQUIPO"): "MAQUINARIA Y EQUIPO",
    ("SBS SEGUROS COLOMBIA SA", "MULTIRIESGO COPROPIEDADES"): "COPROPIEDADES",
    ("SBS SEGUROS COLOMBIA SA", "MULTIRIESGO RESIDENCIAL"): "HOGAR",
    ("SBS SEGUROS COLOMBIA SA", "RESPONSABILIDAD CIVIL"): "RC EXTRACONTRACTUAL",
    
    # -------------------------------------------------------------------------
    # SEGUROS BOLIVAR
    # -------------------------------------------------------------------------
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "ARL"): "ARL",
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "RESPONSABILIDAD CIVIL"): "RC DERIVADA DE CUMPLIMIENTO",
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "SALUD FAMILIAR"): "SALUD FAMILIAR",
    ("COMPAÑIA DE SEGUROS BOLIVAR SA", "VIDA INDIVIDUAL"): "GRUPO COLECTIVO",
    
    # -------------------------------------------------------------------------
    # SEGUROS DEL ESTADO
    # -------------------------------------------------------------------------
    ("SEGUROS DEL ESTADO SA", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("SEGUROS DEL ESTADO SA", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("SEGUROS DEL ESTADO SA", "INCENDIO"): "MULTIRIESGO EMPRESARIAL",
    ("SEGUROS DEL ESTADO SA", "MANEJO"): "MANEJO",
    ("SEGUROS DEL ESTADO SA", "MULTIRIESGO COPROPIEDADES"): "COPROPIEDADES",
    ("SEGUROS DEL ESTADO SA", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("SEGUROS DEL ESTADO SA", "RESPONSABILIDAD CIVIL"): "RC DERIVADA DE CUMPLIMIENTO",
    ("SEGUROS DEL ESTADO SA", "SOAT"): None,  # No disponible
    ("SEGUROS DEL ESTADO SA", "TRANSPORTES DE MERCANCIAS"): "PREDIOS LABORES Y OPERACIONES",
    
    ("SEGUROS DE VIDA DEL ESTADO", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    
    # -------------------------------------------------------------------------
    # SURAMERICANA - GENERALES
    # -------------------------------------------------------------------------
    ("SEGUROS GENERALES SURAMERICANA S A", "AUTOMOVILES"): "AUTOS INDIVIDUAL",
    ("SEGUROS GENERALES SURAMERICANA S A", "CUMPLIMIENTO"): "CUMPLIMIENTO",
    ("SEGUROS GENERALES SURAMERICANA S A", "INCENDIO"): "MULTIRIESGO EMPRESARIAL",
    ("SEGUROS GENERALES SURAMERICANA S A", "MANEJO"): "MANEJO",
    ("SEGUROS GENERALES SURAMERICANA S A", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("SEGUROS GENERALES SURAMERICANA S A", "MULTIRIESGO RESIDENCIAL"): "HOGAR",
    ("SEGUROS GENERALES SURAMERICANA S A", "PROTECCION DIGITAL"): "PROTECCION DIGITAL",
    ("SEGUROS GENERALES SURAMERICANA S A", "RC CLINICAS Y HOSPITALES"): "RC CLINICAS Y HOSPITALES",
    ("SEGUROS GENERALES SURAMERICANA S A", "RESPONSABILIDAD CIVIL"): "RC DERIVADA DE CUMPLIMIENTO",
    ("SEGUROS GENERALES SURAMERICANA S A", "TRANSPORTE DE VALORES"): "TRANSPORTE DE VALORES",
    ("SEGUROS GENERALES SURAMERICANA S A", "TRANSPORTES DE MERCANCIAS"): "TRANSPORTES DE MERCANCIAS",
    
    # SURAMERICANA - VIDA
    ("SEGUROS DE VIDA SURAMERICANA SA", "ACCIDENTES JUVENILES"): "ACCIDENTES JUVENILES",
    ("SEGUROS DE VIDA SURAMERICANA SA", "ACCIDENTES PERSONALES"): "ACCIDENTES PERSONALES",
    ("SEGUROS DE VIDA SURAMERICANA SA", "ARL"): "ARL",
    ("SEGUROS DE VIDA SURAMERICANA SA", "PLAN COMPLEMENTARIO"): "PLAN COMPLEMENTARIO",
    ("SEGUROS DE VIDA SURAMERICANA SA", "PLAN COMPLEMENTARIO COLECTIVO"): "PLAN COMPLEMENTARIO COLECTIVO",
    ("SEGUROS DE VIDA SURAMERICANA SA", "PLAN COMPLEMENTARIO FAMILIAR"): "PLAN COMPLEMENTARIO",
    ("SEGUROS DE VIDA SURAMERICANA SA", "RENTA EDUCATIVA"): "RENTA EDUCATIVA",
    ("SEGUROS DE VIDA SURAMERICANA SA", "SALUD COLECTIVA"): "SALUD COLECTIVA CLASICO",
    ("SEGUROS DE VIDA SURAMERICANA SA", "SALUD FAMILIAR"): "SALUD CLASICO",  # O GLOBAL, EVOLUCIONA según producto
    ("SEGUROS DE VIDA SURAMERICANA SA", "SALUD PARA TODOS"): "SALUD PARA TODOS",
    ("SEGUROS DE VIDA SURAMERICANA SA", "VIDA GRUPO COLECTIVO"): "VIDA GRUPO CONTRIBUTIVO",
    ("SEGUROS DE VIDA SURAMERICANA SA", "VIDA INDIVIDUAL"): "VIDA GRUPO APORTES",
    
    # -------------------------------------------------------------------------
    # ZURICH
    # -------------------------------------------------------------------------
    ("ZURICH COLOMBIA SEGUROS SA", "AERONAVES CASCO"): None,  # No disponible
    ("ZURICH COLOMBIA SEGUROS SA", "MULTIRIESGO EMPRESARIAL"): "MULTIRIESGO EMPRESARIAL",
    ("ZURICH COLOMBIA SEGUROS SA", "MULTIRIESGO RESIDENCIAL"): "HOGAR DEUDOR",
    ("ZURICH COLOMBIA SEGUROS SA", "RESPONSABILIDAD CIVIL"): "RC DIRECTORES Y ADMINISTRADORES",
}


def obtener_aseguradora_maviso(aseguradora_celer: str, ramo_celer: str) -> str:
    """
    Obtiene la aseguradora de MAVISO correspondiente, considerando si debe ir
    a la entidad de VIDA o GENERALES según el ramo.
    """
    if aseguradora_celer in ASEGURADORAS_DOBLES:
        config = ASEGURADORAS_DOBLES[aseguradora_celer]
        if ramo_celer in config["ramos_vida"]:
            return config["aseguradora_vida"]
        else:
            return config["aseguradora_general"]
    
    return MAPEO_ASEGURADORAS.get(aseguradora_celer)


def obtener_subramo_maviso(aseguradora_maviso: str, ramo_celer: str) -> str:
    """
    Obtiene el subramo de MAVISO correspondiente al ramo de CELER.
    Retorna None si no hay mapeo definido.
    """
    return MAPEO_RAMOS.get((aseguradora_maviso, ramo_celer))


# =============================================================================
# LISTA DE SUBRAMOS VÁLIDOS POR ASEGURADORA (extraído de dropdown_list)
# =============================================================================
SUBRAMOS_VALIDOS = {
    "ALLIANZ SEGUROS DE VIDA SA": [
        "ACCIDENTES PERSONALES", "PLAN CREDITO PROTEGIDO", "SALUD COLECTIVA",
        "SALUD MEDICALL CARE", "SALUD MEDICALL GOLD", "SALUD MEDICALL PLUS",
        "VIDA ACTUAL", "VIDA DEUDORES", "VIDA GRUPO APORTES", "VIDA GRUPO CONTRIBUTIVA",
        "VIDA GRUPO DEUDORES", "VIDA GRUPO NO CONTRIBUTIVA"
    ],
    "ALLIANZ SEGUROS SA": [
        "AUTOS COLECTIVO", "AUTOS INDIVIDUAL", "AUTOS PESADOS", "HOGAR", "HOGAR DEUDOR",
        "INFIDELIDAD DE RIESGSOS FINANCIEROS", "MANEJO", "MOTO", "MULTIRRIESGO EMPRESARIAL",
        "NAVEGACIÓN", "PREDIOS LABORES Y OPERACIONES", "RC CLINICAS Y HOSPITALES",
        "RC DIRECTORES Y ADMINISTRADORES", "RC HIDROCARBUROS", "RC TRAYECTOS", "Salud",
        "Todo riesgo", "Transporte", "TRANSPORTE DE MERCANCIAS AUTOMATICAS",
        "TRANSPORTE DE VALORES", "TRANSPORTES DE MERCANCIAS"
    ],
    "ASEGURADORA SOLIDARIA DE COLOMBIA": [
        "ACCIDENTES JUVENILES", "ACCIDENTES PERSONALES", "ARRENDAMIENTO", "AUTOS COLECTIVO",
        "AUTOS INDIVIDUAL", "COPROPIEDADES", "CUMPLIMIENTO", "HOGAR",
        "INFIDELIDAD DE RIESGSOS FINANCIEROS", "MANEJO", "MAQUINARIA Y EQUIPO",
        "MULTIRIESGO EMPRESARIAL", "RC CLINICAS Y HOSPITALES", "RC DERIVADA DE CUMPLIMIENTO",
        "RC DIRECTORES Y ADMINISTRADORES", "RC PREDIOS LABORES Y OPERACIONES",
        "RC SERVIDORES PUBLICOS", "RESPONSABILIDAD CIVIL PROFESIONAL", "SOAT",
        "TODO RIESGO DAÑOS MATERIALES", "TODO RIESGO EN CONSTRUCCION", "TRANSPORTE DE VALORES",
        "TRANSPORTES DE MERCANCIAS", "TRANSPORTES DE MERCANCIAS ESPECIFICAS",
        "UTILITARIOS Y PESADOS", "VIDA GRUPO CONTRIBUTIVO", "VIDA GRUPO DEUDORES",
        "VIDA GRUPO NO CONTRIBUTIVA"
    ],
    "ASSIST CARD DE COLOMBIA SAS": ["ASSIST CARD"],
    "AXA COLPATRIA SEGUROS DE VIDA SA": [
        "ARL", "MAS VIDA", "PLAN CREDITO PROTEGIDO", "SALUD COLECTIVA", "SALUD FAMILIAR",
        "VIDA GRUPO CONTRIBUTIVA", "VIDA GRUPO DEUDOR"
    ],
    "AXA COLPATRIA SEGUROS SA": [
        "ARL", "AUTOS INDIVIDUAL", "AUTOS PESADOS", "COPROPIEDADES", "MOTO",
        "MULTIRIESGO EMPRESARIAL", "Salud", "Todo riesgo", "Transporte"
    ],
    "CHUBB SEGUROS COLOMBIA SA": [
        "ACCIDENTES PERSONALES", "MULTIRRIESGO EMPRESARIAL", "PREDIOS LABORES Y OPERACIONES",
        "RC DIRECTORES Y ADMINISTRADORES", "VIDA GRUPO CONTRIBUTIVA", "VIDA GRUPO NO CONTRIBUTIVA"
    ],
    "COLMENA SEGUROS": ["ARL COLMENA", "SEGUROS EXEQUIALES", "VIDA GRUPO"],
    "COMPAÑIA DE MEDICINA PREPAGADA COLSANITAS SA": ["MEDICINA PREPAGADA COLECTIV"],
    "COMPAÑIA DE SEGUROS BOLIVAR SA": [
        "ACCIDENTES PERSONAL", "ARL", "AUTOS COLECTIVO", "AUTOS INDIVIDUAL", "CUMPLIMIENTO",
        "GRUPO COLECTIVO", "MULTIRIESGO EMPRESARIAL", "PLAN CREDITO PROTEGIDO",
        "RC DERIVADA DE CUMPLIMIENTO", "SALUD FAMILIAR"
    ],
    "COOMEVA EXPERIENCIA MEDICA SAS": ["CEM", "MEDICINA PREPAGADA FAMILIAR"],
    "COOMEVA MEDICINA PREPAGADA SA": ["AREA PROTEGIDA", "MEDICINA PREPAGADA COLECTIV", "MEDICINA PREPAGADA FAMILIAR"],
    "EMERMEDICA SA SERVICIOS DE AMBULANCIA PREPAGADOS": ["EMERGENCIAS MÉDICAS"],
    "FUNERARIA SAN VICENTE SA": ["SEGUROS EXEQUIALES"],
    "GRANCOLOMBIANA DE FIANZAS SAS": ["ARRENDAMIENTO", "CUMPLIMIENTO", "RC DERIVADA DE CUMPLIMIENTO", "RESPONSABILIDAD CIVIL"],
    "HDI SEGUROS": [
        "ACCIDENTES PERSONAL", "AUTOS INDIVIDUAL", "AUTOS PESADOS", "COPROPIEDADES",
        "GRUPO COLECTIVO", "HOGAR", "HOGAR DEUDOR", "MANEJO", "MASCOTAS", "MOTO",
        "MULTIRIESGO EMPRESARIAL", "PLAN CREDITO PROTEGIDO", "PREDIOS LABORES Y OPERACIONES",
        "Salud", "Transporte", "TRANSPORTE DE VALORES", "TRANSPORTES DE MERCANCIAS", "Vida"
    ],
    "LA EQUIDAD SEGUROS GENERALES": ["ACCIDENTES PERSONALES", "AUTOS COLECTIVO", "AUTOS INDIVIDUAL", "MANEJO", "MULTIRIESGO EMPRESARIAL"],
    "LA PREVISORA S A COMPAÑIA DE SEGUROS": [
        "AUTOS INDIVIDUAL", "AUTOS PESADOS", "CUMPLIMIENTO", "MANEJO", "MULTIRIESGO EMPRESARIAL",
        "RC PREDIOS LABORES Y OPERACIONES", "VIDA GRUPO COLECTIVO"
    ],
    "MAGENTA ASISTANCE SAS": ["ACCIDENTES PERSONALES", "EMERGENCIAS MÉDICAS"],
    "MAPFRE SEGUROS GENERALES": [
        "AUTOS COLECTIVO", "AUTOS INDIVIDUAL", "COPROPIEDADES", "HOGAR", "MOTO",
        "MULTIRIESGO EMPRESARIAL", "TRANSPORTE DE VALORES", "TRANSPORTES DE MERCANCIAS", "VIDA"
    ],
    "MEDISANITAS SAS COMPAÑIA DE MEDICINA PREPAGADA": ["MEDICINA PREPAGADA"],
    "MOK": ["ASISTENCIA MEDICA"],
    "POSITIVA COMPAÑIA DE SEGUROS SA": ["ACCIDENTES ESCOLARES", "ARL"],
    "SBS SEGUROS COLOMBIA SA": [
        "ACCIDENTES PERSONAL", "AUTOS COLECTIVO", "AUTOS INDIVIDUAL", "COPROPIEDADES",
        "HOGAR", "MANEJO", "MAQUINARIA Y EQUIPO", "MOTO", "MULTIRIESGO EMPRESARIAL",
        "RC CONTRACTUAL", "RC EXTRACONTRACTUAL", "RC PREDIOS LABORES Y OPERACIONES"
    ],
    "SEGUROS DE VIDA DEL ESTADO": ["ACCIDENTES PERSONALES"],
    "SEGUROS DE VIDA SURAMERICANA SA": [
        "ACCIDENTES JUVENILES", "ACCIDENTES PERSONALES", "ARL", "EXEQUIAL COLECTIVO",
        "PLAN COMPLEMENTARIO", "PLAN COMPLEMENTARIO COLECTIVO", "PLAN CREDITO PROTEGIDO",
        "PLAN VIVE", "RENTA EDUCATIVA", "SALUD CLASICO", "SALUD COLECTIVA CLASICO",
        "SALUD COLECTIVA GLOBAL", "SALUD EVOLUCIONA", "SALUD GLOBAL", "SALUD PARA DOS",
        "SALUD PARA TODOS", "SEGUROS EXEQUIALES", "VIDA GRUPO APORTES", "VIDA GRUPO CONTRIBUTIVO",
        "VIDA GRUPO DEUDOR", "VIDA GRUPO NO CONTRIBUTIVA"
    ],
    "SEGUROS DEL ESTADO SA": [
        "AUTOS COLECTIVO", "AUTOS INDIVIDUAL", "COPROPIEDADES", "CUMPLIMIENTO",
        "DIRECTORES Y ADMINISTRADORES", "MANEJO", "MULTIRIESGO EMPRESARIAL",
        "PREDIOS LABORES Y OPERACIONES", "RC DERIVADA DE CUMPLIMIENTO"
    ],
    "SEGUROS GENERALES SURAMERICANA S A": [
        "ACCIDENTES JUVENILES", "ARL", "ASISTENCIA EN VIAJE", "AUTOS COLECTIVO",
        "AUTOS INDIVIDUAL", "COPROPIEDADES", "CUMPLIMIENTO", "HOGAR", "HOGAR DEUDOR",
        "INFIDELIDAD DE RIESGSOS FINANCIEROS", "MANEJO", "MAQUINARIA Y EQUIPO", "MOTO",
        "MULTIRIESGO EMPRESARIAL", "PREDIOS LABORES Y OPERACIONES", "PROTECCION DIGITAL",
        "RC CLINICAS Y HOSPITALES", "RC DERIVADA DE CUMPLIMIENTO", "RC DIRECTORES Y ADMINISTRADORES",
        "RC PROFESIONAL CONTADORES", "RC PROFESIONAL MEDICOS", "RC PROFESIONAL VETERINARIOS",
        "RENTA EDUCATIVA", "RENTA PENSIONAL", "ROTURA MAQUINARIA", "SALUD PARA TODOS",
        "SEGUROS EXEQUIALES", "TODO RIESGO EN CONSTRUCCION", "TRANSPORTE DE VALORES",
        "TRANSPORTES DE MERCANCIAS", "TRANSPORTES DE MERCANCIAS ESPECIFICO", "UTILITARIOS Y PESADOS"
    ],
    "SEGUROS MUNDIAL": [
        "ACCIDENTES PERSONAL", "ARRENDAMIENTO", "AUTOS INDIVIDUAL", "AUTOS PESADOS",
        "CUMPLIMIENTO", "MAQUINARIA Y EQUIPOS DE CONT", "RC DERIVADA DE CUMPLIMIENTO",
        "SEGURO EDUCATIVO", "VIDA COLECTIVO"
    ],
    "ZURICH COLOMBIA SEGUROS SA": ["COPROPIEDADES", "HOGAR DEUDOR", "MULTIRIESGO EMPRESARIAL", "RC DIRECTORES Y ADMINISTRADORES"],
}
